export const textStyles = {
  logo: "text-2xl font-bold",
  h1: "text-4xl font-extrabold tracking-tight lg:text-5xl",
  h2: "text-3xl font-semibold tracking-tight",
  h3: "text-2xl font-semibold tracking-tight",
  h4: "text-xl font-semibold tracking-tight",
  p: "text-base font-normal leading-6",
  base: "text-base font-normal",
  lead: "text-xl text-muted-foreground",
  large: "text-lg font-semibold",
  small: "text-sm font-medium leading-none",
  tableLink: "text-sm font-medium leading-none hover:underline",
  muted: "text-sm text-muted-foreground",
  mutedLink: "text-sm text-muted-foreground hover:text-slate-700",
};
