import * as Context from "effect/Context";
import type * as Effect from "effect/Effect";
import type { ExternalServiceError } from "@/src/common/effect/errors";
import type { NoteRowModel } from "@/src/notes/domain/models/note-row-model";
import type {
  AiGeneratorEmptyMessageError,
  AiGeneratorError,
  AiGeneratorRateLimitError,
} from "../errors/ai-generator-errors";
import type { AiGeneratorNoteType } from "../models/ai-generator-note-type";
import type { AiNotesGeneratorSourceType } from "../models/ai-notes-generator-source-type";

/**
 * Generates notes automatically from a certain text or topic.
 * Leverages the capabilities of an LLM (Large Language Model) to
 * create the results.
 */
export interface AiNotesGeneratorService {
  /**
   * Generates a list of notes from a set of parameters
   * @param input Configuration of the AI generator, including the text or topic
   * @returns A list of notes generated by the AI. Each note is a tuple
   * consisting of two strings: the question (front side of the note) and the
   * answer (back side of the note)
   */
  generate(
    input: GenerateAiNotesInputModel,
  ): Effect.Effect<
    NoteRowModel[],
    | ExternalServiceError
    | AiGeneratorEmptyMessageError
    | AiGeneratorRateLimitError
    | AiGeneratorError
  >;
}

/**
 * Configuration of the AI generator
 */
export interface GenerateAiNotesInputModel {
  /**
   * Text or topic that serves as prompt to the AI
   */
  text: string;
  /**
   * List of types of notes to generate (i.e. definitions, questions, lists)
   */
  noteTypes: AiGeneratorNoteType[];
  /**
   * Number of notes to generate. Warning: the AI model is unpredictable and
   * might generate more or less notes than the amount requested.
   */
  notesCount: number;
  /**
   * The source used to get the `text` parameter. It can be a file, a text or a
   * topic.
   */
  sourceType: AiNotesGeneratorSourceType;
}

export const AiNotesGeneratorService = Context.Service<AiNotesGeneratorService>(
  "clubmemo/ai-generator/domain/interfaces/ai-notes-generator-service/AiNotesGeneratorService",
);
